blackjax/__init__.py
blackjax/hmc.py
blackjax/inference/__init__.py
blackjax/inference/base.py
blackjax/inference/integrators.py
blackjax/inference/metrics.py
blackjax/inference/proposals.py
mypy.ini
tests/test_hmc.py
tests/test_integrators.py

Implement a HMC kernel that moves one chain for one step, with the following elements:
The goal is to get to a concrete implementation quickly to see the design in action.

implement the HMC kernel

---

blackjax/inference/metrics.py
blackjax/inference/termination.py
blackjax/inference/trajectory.py
tests/test_trajectory.py

- change deprecated index_update ops (https://jax.readthedocs.io/en/latest/jax.ops.html#indexed-update-functions-deprecated)
- bug fix of u turn check (it was not checking on the resulting merged trajectory)
- refactored the merging of 2 trajectory so it is easier to add robust u-turn check

Bug fix in NUTS sampler

---

blackjax/hmc.py
blackjax/inference/proposal.py
blackjax/inference/trajectory.py
blackjax/nuts.py
setup.py
tests/test_compilation.py
tests/test_hmc.py
tests/test_trajectory.py

This PR fix a few major bugs in NUTS implementation
- Proposal weight need to be accumulated regardless accept or reject
- During tree doubling, the trajectory of a new tree should not include the state that initialise the new tree
- There is a bug that during trajectory building integration was starting from the proposal position instead of the previous position in the trajectory
- Energy differences should be compare with the initial state of the step, not the proposal state or the state that initialise the new tree
- Proposal should comes from a subtree (not including the state that initialise the new tree)

NUTS bug fix

---

blackjax/inference/trajectory.py

Always append the state to the rightmost during progressive integration and only flip the 2 end when integration is terminated.

Small refactor so we do less control flow

---

blackjax/stan_warmup.py

pass step size and inv mass mat as args, not kwargs

---

blackjax/__init__.py
blackjax/diagnostics.py
tests/test_diagnostics.py
tests/test_sampling.py

Add basic diagnostics
- computation of r-hat
- computation of effective sample size (not based on rank, but easy to add)
- add test to validate sampler accuracy base on monte carlo CLT.
It handles shape flexibly as chain dimension and sample dimension is arbitrary. For example, arviz requires the input array to be [chain, sample, dim0], here we can do [chain, sample, dim0, dim1, ...] or [sample, chain, dim0, dim1, ...], which works both for vmap and pmap output (or even [sample, dim0, dim1, dim2, ..., chain]) 
The diagnostics can be jitted so we can potentially put it in a larger sampling/tuning routine.

Add diagnostics

---

blackjax/adaptation/step_size.py
blackjax/stan_warmup.py

This PR exposes two arguments for step size adaptation to the function `stan_warmup.run`:
- `target_accept_initial` for initial step size adaptation i.e. passed to `find_reasonable_step_size`,
- `target_accept` for step size adaptation using dual averaging i.e. passed to `dual_averaging_adaptation`
Closes #109

Expose `target_accept` arguments to `stan_warmup.run`

---

blackjax/inference/smc/resampling.py
tests/test_resampling.py

This reuses our previous implementation of multinomial instead of the high memory footprint implementation of categorical sampling. The difference now lies in the use of a permutation of the multinomial indices to make sure that the sorted uniforms don't mess with the exchangeability properties.
It is probably best to merge this prior to the Waste-free SMC.

Better residual resampling

---

.github/workflows/test.yml
requirements.txt

Github was skipping testing because of bug on test workflow.

Bugfix in test workflow

---

.pre-commit-config.yaml

This is not useful since the master branch is protected.

Remove the `no-commit-to-branch` check in pre-commit

---

README.md
examples/Introduction.ipynb
requirements.txt

Very small change, was going through the `contributing` setup page (I'd like to add SMC ABC to this) and noticed that `requirements-dev.txt` does not exist anymore.

Fix install instructions in README

---

blackjax/kernels.py
blackjax/progress_bar.py
examples/use_with_pymc.ipynb
requirements.txt
setup.py
tests/test_sampling.py

This adapts @jeremiecoullon progress bar code to allow progress bars to be displayed during adaptation. Like in numpyro they can have an adverse effect on sampling time so should be disabled for benchmarking.
If we think progress bars are out of scope for blackjax this can be refactored to take `progress_bar_scan` shaped callback instead.

Adding progress bars to window adaptation

---

blackjax/mcmc/mala.py
tests/test_sampling.py

Make MALA work with any PyTree

---

.github/workflows/test.yml
README.md
requirements-jax.txt
setup.py

Closes #212. Issue also mentioned in #225.

Add JAX and JAXOpt to library requirements

---

blackjax/optimizers/lbfgs.py
blackjax/vi/pathfinder.py

This addresses https://github.com/blackjax-devs/blackjax/issues/227.
It passes tests locally on my machine, but should probably add an explicit test for a more complex pytree input. Let me know your thoughts.
One thing I'm not sure about is whether you want to count on `LbfgsState` being a stable feature of `jaxopt`. It might make sense to only unravel the fields in `LBFGSHistory`.

Tweak LBFGS to allow PyTree inputs

---

tests/test_smc_ess.py

This is my first PR to Blackjax. I realized that the ESS calculation code only had a univariate, single variable posterior test case so I am adding a multivariate and multivariable test cases. I think this adds value from the correctness but also from the interpretability point of view (I wasn't sure the functionality was in place).
- [N/A] There are links to *all* the relevant issues, discussions and PRs;
- [YES] The branch is rebased on the latest `main` commit;
- [YES] `pre-commit` is installed and configured on your machine, and you ran it before opening the PR;
- [YES] There are tests covering the changes;
- [N/A ] If I add a sampler I added/updated related …

SMC ESS calculation multivariate and multivariable posterior tests.

---

blackjax/__init__.py
blackjax/kernels.py
blackjax/mcmc/__init__.py
blackjax/mcmc/marginal_latent_gaussian.py
docs/examples.rst
examples/LogisticRegressionWithLatentGaussianSampler.ipynb
tests/test_latent_gaussian.py
tests/test_sampling.py

This is a clean up of the commit history of https://github.com/blackjax-devs/blackjax/pull/228, implementing the marginal sampler of https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssb.12269.

Add Gradient based sampler for latent Gaussian models

---

blackjax/sgmcmc/diffusion.py

The latter is deprecated in jax and will be removed in https://github.com/google/jax/pull/11382
Note that in the last several JAX releases, `tree_multimap` is a direct alias of `tree_map`, so this substitution will not result in any change of behavior aside from silencing the deprecation warning (see https://github.com/google/jax/blob/5b576cb03e85f2e4d8d99f314cf5d87981ef5d42/jax/_src/tree_util.py#L198-L202).

Use jax.tree_map in place of jax.tree_multimap

---

blackjax/kernels.py
tests/test_benchmarks.py
tests/test_optimizers.py
tests/test_sampling.py

- Flakyness in optimizer is due to maxcor too low
- Flakyness in linear regression test is due to incorrect logprob function (actually all algorithm in the same test returns bias result)
fix #269

Fix flaky test

---

blackjax/kernels.py
examples/SGMCMC.md
tests/test_sampling.py

The current API requires user to pass a function of the index of the current iteration, even when the learning rate is constant. However, in practice most people use a constant learning rate (even if they shouldn't, but who are we to judge?)  and we should simplify that pattern of use.
This commit thus allows users to pass either a function, either a float as learning rate to the kernel builder. It will raise an exception for any other type.

Allow users to pass a float for constant learning rate

---

.github/workflows/release.yml

The workflow that checks that blackjax can be installed from PyPi currently fails because `$GITHUB_REF` is truncated before the leading version number (currently 0). This commit fixes this.

Truncate `$GITHUB_REF` at the right level when testing for `pip install` success

---

.github/workflows/build_doc.yml
.github/workflows/build_documentation.yml
.github/workflows/publish_documentation.yml
.github/workflows/release.yml
.github/workflows/test.yml

In this PR I allow the CI to build docs on PRs, and do some light cleaning of the workflow files. Closes #294

Build docs in PR and clean workflows

---

docs/conf.py
examples/GP_EllipticalSliceSampler.md
examples/Introduction.md
examples/LogisticRegression.md
examples/LogisticRegressionWithLatentGaussianSampler.md
examples/Pathfinder.md
examples/PeriodicOrbitalMCMC.md
examples/RegimeSwitchingModel.md
examples/SGMCMC.md
examples/SparseLogisticRegression.md
examples/TemperedSMC.md
examples/change_of_variable_hmc.md
examples/howto_use_aesara.md
requirements-doc.txt

Reminding here that environment information is not necessary since this can be found in the CI process that generated the doc.
Closes #308 and #309

Fix math and remove environment information in documentation

---

README.md

Updated the link to the [introductory notebook](https://github.com/blackjax-devs/blackjax/blob/main/examples/Introduction.md). Let me know if that's the correct one.
Looking forward to learning more about BlackJAX. Keep up the good work!

Fix broken link to introduction notebook in README

---

.github/workflows/publish_documentation.yml

We would ideally need a new version of the documentation for each minor version plus one for `HEAD` (#313). In the meantime, the best default is to have the documentation refer to the last release on PyPi. This PR changes the publication workflow so docs is only published on each new release.

Only publish the docs on release

---

docs/index.rst
examples/howto_other_frameworks.md
requirements-doc.txt

Use an Aesara model compiled to Numba with Blackjax. The example is currently very slow, even after calling `jax.jit` on the NUTS kernel, even though the Numba logp evaluates faster thant its JAX equivalent.
Closes #318

Add How-to reference on using logpdf built with another framework

---

examples/Introduction.md

This PR addresses typo discussed here https://github.com/blackjax-devs/blackjax/issues/366

Fix documentation typo for kernel and state input

---

blackjax/adaptation/meads.py
blackjax/adaptation/pathfinder_adaptation.py
blackjax/kernels.py
blackjax/mcmc/diffusion.py
blackjax/mcmc/ghmc.py
blackjax/mcmc/hmc.py
blackjax/mcmc/integrators.py
blackjax/mcmc/nuts.py
docs/index.rst
examples/howto_custom_gradients.md
tests/test_integrators.py
tests/test_sampling.py

Custom gradient currently need to be passed to the algorithms all the way down to the integrators. However JAX has a much nicer way of doing that; you can write a logprob and register a gradient for that logprob; JAX will then use it when `jax.grad` is called on that function.
Closes #341 #318

Remove `logprob_grad_fn` kwargs in favor of `jax.custom_vjp`

---

tests/test_benchmarks.py

Close #379.
Further improvement of benchmark will be tracked in #163

Fix benchmark

---

blackjax/adaptation/window_adaptation.py
blackjax/mcmc/diffusion.py
blackjax/mcmc/elliptical_slice.py
blackjax/mcmc/ghmc.py
blackjax/mcmc/mala.py
blackjax/mcmc/metrics.py
blackjax/mcmc/rmh.py
blackjax/sgmcmc/diffusion.py
blackjax/sgmcmc/sghmc.py
blackjax/util.py
tests/test_proposal.py

... that is the same PyTree structure as the input.
relate to #376

Refactor the function for generating Gaussian noise

---

blackjax/adaptation/meads.py
blackjax/kernels.py
blackjax/mcmc/ghmc.py
tests/test_sampling.py

Also removing some unused parameters of high-level functions, see #285.
Moved `maximum_eigenvalue` and improved docstring (https://github.com/blackjax-devs/blackjax/pull/229/files#r973546148).
Close #285

Improve batch shape handling in MEADS and allow scaled step sizes in GHMC using `mcmc.integrators.velocity_verlet`

---

examples/Introduction.md
examples/RegimeSwitchingModel.md
examples/SparseLogisticRegression.md
examples/howto_sample_multiple_chains.md
setup.py
tests/test_benchmarks.py
tests/test_optimizers.py
tests/test_sampling.py
tests/test_tempered_smc.py

Closes #378 
As a side note: If initial parameters for the `log_scale` are set to $1.0$ in `regression_test_cases` only `test_pathfinder_adaptation` fails with samples for `log_scale` diverging to `inf`.

Modify linear regressions to parameters in R

---

blackjax/adaptation/step_size.py
blackjax/kernels.py
blackjax/mcmc/ghmc.py
blackjax/mcmc/hmc.py
blackjax/mcmc/mala.py
blackjax/mcmc/marginal_latent_gaussian.py
blackjax/mcmc/nuts.py
blackjax/mcmc/proposal.py
blackjax/mcmc/rmh.py
blackjax/mcmc/trajectory.py
examples/howto_use_numpyro.md
examples/howto_use_tfp.md

In this PR I replace the use of "acceptance_probability" with "acceptance_rate" which is more generally applicable, e.g. with NUTS. Closes #290

S/acceptance probability/acceptance ratio

---

blackjax/__init__.py
blackjax/base.py
blackjax/kernels.py
blackjax/optimizers/lbfgs.py
blackjax/vi/pathfinder.py
examples/Pathfinder.md
examples/change_of_variable_hmc.md
tests/test_pathfinder.py

In this PR I update the pathfinder API to fit the variational inference semantics more closely. The `init`, `kernel` terminology is not adapted to variational inference: instead of using a markov kernel to update the state, vi algorithms compute an approximation to the target distribution and then sample from this approximation.
I thus propose the following API for pathfinder:
```python
import blackjax
pathfinder = blackjax.pathfinder(logprob_fn)
approximation, info = pathfinder.approximate(rng_key, initial_position)
samples, _ = pathfinder.sample(rng_key, approximation, num_samples)
```
Where `info` contains the full path (which is thus always returned), I created a new `VISamplingAlgorithm` type, and made a few simplifying tweaks to the implementation of pathfinder. Closes #282

Update the pathfinder API

---

docs/_static/custom.css
docs/conf.py

Makes the API documentation breathe a little bit.

Add linebreak between function params in API doc

---

examples/GP_EllipticalSliceSampler.md
examples/GP_Marginal.md

Closes https://github.com/blackjax-devs/blackjax/issues/238 
**Aim:** Use the data from https://blackjax-devs.github.io/blackjax/examples/GP_EllipticalSliceSampler.html to illustrate the implementation introduced in https://github.com/blackjax-devs/blackjax/pull/247 
For now, I have a running notebook that runs the example. I still wanted to push this branch and create a draft PR for feedback. What is missing (IMO):
**General**
**Details**
Any feedback is welcome :)

Use the new marginal sampler for latent gaussian models in the GP notebook

---

examples/howto_use_pymc.md
requirements-doc.txt

This is just a minor fix to make the pymc example work again.

Fix pymc example

---

blackjax/kernels.py
docs/howto_use_ppl.rst
examples/SGMCMC.md
examples/howto_use_numpyro.md
examples/howto_use_tfp.md

- example using oyrx is currently broken (https://github.com/jax-ml/oryx/issues/25)

Minor doc clean up

---

.github/workflows/test.yml
.gitlint
.pre-commit-config.yaml

Configuration of a gitlint according to the rules described in https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html.
Closes #420

Gitlint configuration

---

.github/ISSUE_TEMPLATE/meeting.md
.github/workflows/schedule-meeting.yml

We will be hosting Blackjax meetings every first Friday of the month. In this PR I add a github action that opens a new issue the 20th of the month with the video link, so people can add items to the agenda.

Automatically open an issue for Blackjax meetings

---

blackjax/__init__.py
blackjax/base.py
blackjax/kernels.py
blackjax/vi/__init__.py
blackjax/vi/meanfield_vi.py
docs/vi.rst
pyproject.toml
pytest.ini
tests/test_meanfield_vi.py

Some initial attempts in integrating MFVI into blackjax https://github.com/blackjax-devs/blackjax/issues/397.
TODO:
There is going to be lots of boiler plate code shared between MFVI and Fullrank VI.
It is also worth considering how to add stick-the-landing gradient estimator [1] and importance-weighted ELBO optimization [2].
[1] Roeder, Geoffrey, Yuhuai Wu, and David K. Duvenaud. "Sticking the landing: Simple, lower-variance gradient estimators for variational inference." Advances in Neural Information Processing Systems 30 (2017).
[2] Domke, Justin, and Daniel R. Sheldon. "Importance weighting and variational inference." Advances in neural information processing systems 31 (2018).

Add Mean Field Variational Inference implementation 

---

docs/examples/howto_use_oryx.md

The Oryx example is currently taking several minutes to run because of the number of parameters of the Neural Network it is sampling from. I drastically reduced the number of parameters, we still get an decent accuracy.

Simplify the Oryx examples

---

.github/workflows/benchmark.yml

We use https://github.com/benchmark-action/github-action-benchmark to benchmark the code both on PR and push on `main`. The results from previous runs are stored in cache and committed to gh-pages.

Use github-action-benchmark for continous benchmarking

---

requirements-doc.txt

Resolves #303 and #364.
By removing `distrax`, we can unify the way the code is written.
`tensorflow-datasets` is no longer necessary as example code moves to sampling-book. (btw, huggingface datasets is lightweight and meets requirements)

Remove unnecessary dependency

---

blackjax/types.py

Use public JAX API for PRNGKeyArray

---

.readthedocs.yaml

Read the Docs builds are currently failing because the build is issuing warnings and we set `fail_on_warning` to `True`. Let's set it to `False` temporarily to get the docs building and figure out the reasons for the warnings later.

Do not fail RTD build on warning

---

blackjax/types.py

use chex for typing

---

.github/workflows/release.yml
.github/workflows/test.yml
pyproject.toml
requirements-doc.txt

The latest release of JAX raises an error for the use of any deprecated version of `jax.Array`. This creates errors in tests when importing optax (the latest release is from Nov 2022). In the latests developments of the library this is fixed, so we now install these latests developments instead of the latests release.
We could install an earlier version of JAX, instead of the latest developments of optax.

Drop support of Python 3.7 and install latest developments of optax to avoid failing tests

---

blackjax/kernels.py
blackjax/sgmcmc/csgld.py
tests/mcmc/test_sampling.py

Pass `grad_estimator` to the CSGLD kernel directly

---

blackjax/mcmc/mala.py
blackjax/mcmc/proposal.py

Refactor MALA so that it uses the MH component in proposals.py

---

blackjax/kernels.py
blackjax/mcmc/random_walk.py
tests/mcmc/test_random_walk_without_chex.py
tests/smc/test_kernel_compatibility.py

Some kernel interfaces weren't compatible with SMC. This PR fixes them and adds a test that protects us from regressions that may break the integration between the MCMC kernels and SMC. If we believe a kernel could be used within SMC, then it should be added to this test.

SMC-MCMC integration test, plus fixes.

---

docs/_static/custom.css

This reverts commit 6963ecfc8b7a727f65e9e77272936180209660a8.
With the background-color added in custom.css the documentation page in dark mode is displayed like this.

Revert "Change documentation background color"

---

blackjax/mcmc/trajectory.py
tests/mcmc/test_trajectory.py

It is common practice to jitter the integration lengths HMC sampling for each proposal, but as currently written, BlackJAX's implementation of HMC doesn't support this. This tiny PR adds support for non-static integration lengths by converting the `scan` that currently backs the HMC proposal integration to a `fori_loop` which supports both static and variable numbers of steps. In the case where a static number is passed, `fori_loop` automatically rewrites itself as the `scan` that was previously used so I don't expect this to introduce any changes for the currently supported use case.
I don't believe this has been previously discussed, but I'm happy to chat if anyone has suggestions!
---
Consider opening a **Draft …

Converting scan to fori_loop in static_integration in order to support a variable number of integration steps in HMC sampler

---

blackjax/__init__.py
blackjax/vi/__init__.py
blackjax/vi/svgd.py
docs/refs.bib
tests/vi/test_svgd.py

As discussed in #385.
Done:
- Implementation of the algorithm
- Added very simple (bad) test.
TODO:
- Add an example with GPU where gradients is calculated with pmap.
- How to take mini batch gradients? 
- Come up with a better test.
**Appreciate any comments & feedback!**
- [ X ] *If I add a new sampler*, there is an issue discussing it already;
- [ X ] We should be able to understand what the PR does from its title only;
- [ X ] There is a high-level description of the changes;
- [ X ] There are links to *all* the relevant issues, discussions and PRs;
- [ X ] The branch is rebased on the latest `main` commit;
- [ X ] `pre-commit` is installed and configured on your machine, and you ran it before opening the PR;
- [ …

SVGD implementation

---

blackjax/adaptation/meads_adaptation.py
blackjax/mcmc/ghmc.py
blackjax/sgmcmc/csgld.py
blackjax/sgmcmc/diffusions.py
blackjax/sgmcmc/sghmc.py
blackjax/sgmcmc/sgld.py
blackjax/sgmcmc/sgnht.py
tests/mcmc/test_sampling.py

As discussed in #537 , this PR unifies the `sgmcmc` module such that all algorithms have an `init` function and return a `MCMCSamplingAlgorithm`, in the case of `sgld` and `sghmc` the init function is the trivial `lambda position: position`.
This does not result in totally seamless switching since some algorithms (`sgnht` and `csgld`) require a `rng_key` whereas others do not. However, the block to seamless switching is not just down to the `init` since some algorithms (`csgld`) also require custom `step_fun` signatures.
I have reordered the `init` signatures such that `position` is first, `rng_key` is second (if required) followed by any other 
algorithm-specific arguments. This included a refactor to `ghmc` and as a results `meads_adaptation`.
I suggest that possibly we should consider …

Unify SGMCMC init structure

---

blackjax/base.py
blackjax/mcmc/elliptical_slice.py
blackjax/mcmc/ghmc.py
blackjax/mcmc/hmc.py
blackjax/mcmc/mala.py
blackjax/mcmc/marginal_latent_gaussian.py
blackjax/mcmc/nuts.py
blackjax/mcmc/periodic_orbital.py
blackjax/mcmc/random_walk.py
blackjax/sgmcmc/csgld.py
blackjax/sgmcmc/sghmc.py
blackjax/sgmcmc/sgld.py
blackjax/sgmcmc/sgnht.py
blackjax/smc/adaptive_tempered.py
blackjax/smc/tempered.py
blackjax/vi/svgd.py

`MCMCSamplingAlgorithm` -> `SamplingAlgorithm`

---

blackjax/mcmc/nuts.py

Implement #564 
1. Making the argument consistent with 'num_integration_steps' in HMC
2. Allows running adaptation (e.g. `window_adaptation`) with an arbitrary `max_num_doublings` 
---

Moving max_num_doublings of NUTS from build_kernel to kernel

---

docs/examples/howto_metropolis_within_gibbs.md

Update the Metropolis-within-Gibbs example markdown notebook to be compatible with API changes, as mentioned  in #551.
Included a function that takes the variance of a normal distribution as a parameter and returns a RMH kernel with a normal proposal generator. Also added minor changes to text to keep consistency with updates. I have a couple more thoughts for a few more minor edits, so I'm opening this up a draft PR (also I'm a first time contributor).
potential (nitpicky) edits:
- `AlgorithmState` is mentioned, but is this an actual object in the code base referring to some generic class or type? If not, I think it would be better to refer to a generic state as "algorithm state", so its not confused as something in blackjax.
- Change references of `blackjax.mcmc.algorithm.init()` to …

Update the Metropolis-within-Gibbs example 

---

blackjax/types.py
pyproject.toml
requirements-doc.txt
requirements.txt
tests/adaptation/test_step_size.py
tests/mcmc/test_latent_gaussian.py
tests/mcmc/test_metrics.py
tests/mcmc/test_proposal.py
tests/mcmc/test_random_walk_without_chex.py
tests/mcmc/test_sampling.py
tests/mcmc/test_trajectory.py
tests/optimizers/test_optimizers.py
tests/optimizers/test_pathfinder.py
tests/smc/test_kernel_compatibility.py
tests/smc/test_resampling.py
tests/smc/test_smc.py
tests/smc/test_tempered_smc.py
tests/test_benchmarks.py
tests/test_compilation.py
tests/test_diagnostics.py
tests/vi/test_meanfield_vi.py
tests/vi/test_svgd.py

See https://github.com/google/jax/pull/17297/files for background.

Update dependencies and use new jax random key

---

blackjax/mcmc/hmc.py
blackjax/mcmc/mala.py
blackjax/mcmc/proposal.py
blackjax/mcmc/random_walk.py
blackjax/mcmc/trajectory.py
tests/mcmc/test_proposal_without_chex.py
tests/mcmc/test_random_walk_without_chex.py

Fix #391.
The change end up quite small that it do away divergence check in `proposal.py`, and compute divergence only when needed (in `hmc.py` and `trajectory.py`). The functions in `proposal.py` is more general than just HMC that we see pattern like:
```python
new_proposal, _ = generate_proposal(state, end_state)
```
So removing the check would keeps the functions in `proposal.py` simpler and more focus.
However, we cannot push the check the top most level (ie., it need to remain in `trajectory.py`), as the information is used during the trajactory building and it is not easy to refactor it away.

Refactor divergence check to each sampler

---

blackjax/mcmc/random_walk.py
tests/mcmc/test_random_walk_without_chex.py

Adds proposal_logdensity_fn as parameter, so as to modify MH acceptance rule to accommodate for non-symmetry of the proposal distribution.
- [N] *If I add a new sampler*, there is an issue discussing it already;
- [Y] We should be able to understand what the PR does from its title only;
- [Y] There is a high-level description of the changes;
- [N/A] There are links to *all* the relevant issues, discussions and PRs;
- [Y] The branch is rebased on the latest `main` commit;
- [Y] Commit messages follow these [guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html);
- [Y] The code respects the current naming conventions;
- [Y] Docstrings follow the [numpy style …

Adjusts for the fact that IRMH proposal might not be symmetric

---

blackjax/smc/base.py

Documents how particles should be represented in SMC, providing some examples. Hopefully covers what was answered in this dicussion https://github.com/blackjax-devs/blackjax/discussions/464
- [N ] *If I add a new sampler*, there is an issue discussing it already;
- [Y] We should be able to understand what the PR does from its title only;
- [Y ] There is a high-level description of the changes;
- [Y] There are links to *all* the relevant issues, discussions and PRs;
- [ Y] The branch is rebased on the latest `main` commit;
- [Y] Commit messages follow these [guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html);
- [Y] The code respects the current naming conventions;
- [Y] Docstrings …

Document how particles should be represented in SMC

---

blackjax/__init__.py
blackjax/adaptation/__init__.py
blackjax/adaptation/chees_adaptation.py
blackjax/mcmc/hmc.py
docs/refs.bib
tests/adaptation/test_adaptation.py
tests/mcmc/test_sampling.py

Add adaptation on HMC trajectory length to increase the expected Change in the Estimator of the Expected Square (ChEES-HMC)

---

blackjax/mcmc/integrators.py

Changes `EuclideanIntegrator` -> `Integrator`, for more inclusive naming.

EuclideanIntegrator -> Integrator

---

blackjax/mcmc/integrators.py
blackjax/util.py
docs/refs.bib
tests/mcmc/test_integrators.py

Also add momentum update based on Esh dynamics
Close #587

Refactor integrators.py to make it more general.

---

blackjax/adaptation/chees_adaptation.py

Changes the argument name in `chees_adaptation` from `logprob_fn` to `logdensity_fn`.

Name arguments consistently across adaptation classes.

---

Makefile
blackjax/mcmc/barker.py
docs/refs.bib

Does what is says on the tin. I also removed debugging by default in the sphinx-build as it was making things way slower.

Add Barker's proposal reference

---

blackjax/adaptation/mclmc_adaptation.py
blackjax/diagnostics.py
tests/test_diagnostics.py

The `effective_sample_size` implementation already contain safeguarding to compute ess when `num_chain == 1`
close #608 
cc @reubenharry

Losen the input requirement for ess computation.

---

blackjax/util.py
docs/examples/quickstart.md
tests/adaptation/test_adaptation.py
tests/mcmc/test_sampling.py
tests/test_benchmarks.py

Closes #591. Implements a `run_inference_algorithm` wrapper function in `blackjax/util.py` for convenience. See discussion in #591 for more details. 

Resolve 'Functions to run kernels'

---

blackjax/smc/base.py
blackjax/smc/ess.py
blackjax/smc/solver.py
tests/smc/test_kernel_compatibility.py
tests/smc/test_solver.py

Minor clean up for SMC

---

blackjax/util.py
tests/test_util.py

Closes #610. Adds progress bar to `run_inference_algorithm`. 

Resolve: Add progress bar to run_inference_algorithm

---

blackjax/util.py
tests/test_util.py

A first step towards issue #615.
A simple change, in case a user doesn't want to store all the history of the state in a large high dimensional run, for reasons of memory.

Add transform TO `run_inference_loop`

---

blackjax/adaptation/mclmc_adaptation.py
blackjax/base.py
blackjax/mcmc/barker.py
blackjax/mcmc/dynamic_hmc.py
blackjax/mcmc/elliptical_slice.py
blackjax/mcmc/ghmc.py
blackjax/mcmc/hmc.py
blackjax/mcmc/mala.py
blackjax/mcmc/marginal_latent_gaussian.py
blackjax/mcmc/mclmc.py
blackjax/mcmc/nuts.py
blackjax/mcmc/periodic_orbital.py
blackjax/mcmc/random_walk.py
blackjax/sgmcmc/csgld.py
blackjax/sgmcmc/sghmc.py
blackjax/sgmcmc/sgld.py
blackjax/smc/adaptive_tempered.py
blackjax/smc/inner_kernel_tuning.py
blackjax/smc/tempered.py
blackjax/util.py
docs/examples/howto_use_oryx.md
tests/adaptation/test_adaptation.py
tests/mcmc/test_sampling.py
tests/smc/test_inner_kernel_tuning.py

Close #619.
This PR introduce `rng_key` as optional input to `initFn` protocal.
For sampler like `dynamic_hmc` and `ghmc`, the `init_fn` of the top level API does not follow the old patter, as it needs an rng_key to generate part of the `state`. While it is possible to set a default rng_key in the class `__new__`, we actually wants to keep the rng_key as input to `init_fn` as we usually want to vmap init so that it takes a vector of PRNG_key to initialized parallel chains (see eg: in meads_adaptation https://github.com/blackjax-devs/blackjax/blob/08e0d7521b2c06ba29b94a1c186bdaf8c08e6310/blackjax/adaptation/meads_adaptation.py#L209, https://github.com/blackjax-devs/blackjax/blob/08e0d7521b2c06ba29b94a1c186bdaf8c08e6310/blackjax/adaptation/meads_adaptation.py#L239-L240).
Thus, in this PR we …

Extend function signature for InitFn

---

blackjax/mcmc/mclmc.py

Raise a ValueError if the initial position has 1 dimension, because MCLMC (in the rescaled form available in code) only works in 1 dimension.

PREVENT 1D DISTRIBUTION

---

blackjax/mcmc/mala.py

The current MALA transition energy is implemented incorrectly. In fact, the correct one should be the reverse of the current one.
To see that, note that MALA's log acceptance probability is calculated as `prev_energy - new_energy`, with `new_energy` being the transition energy from `initial_state` to `state`. As such, the correct `new_energy` should be `-log p(state) - log q(initial_state|state)`, but the current implementation implements `-log p(initial_state) - log q(state|initial_state)`; the implementation of RWMH seems correct.
Reference: https://en.wikipedia.org/wiki/Metropolis-adjusted_Langevin_algorithm

Fix MALA transition energy

---

blackjax/mcmc/mala.py

A follow-up of this pull request: https://github.com/blackjax-devs/blackjax/pull/653. Change variable names to better reflect the previous pull request that fixes MALA transition energy. Feel free to change it if I missed something 😃

Change variable names

---

blackjax/mcmc/proposal.py

Since [jax 0.4.27](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-27-may-7-2024), `jax.numpy.clip` has a new signature.
Fixes #663

Fix deprecated call to jnp.clip

---

tests/adaptation/test_adaptation.py

Make tests pass on `aarch64-linux` (#668)

Make tests pass on `aarch64-linux`

---

blackjax/adaptation/base.py
blackjax/adaptation/chees_adaptation.py
blackjax/adaptation/meads_adaptation.py
blackjax/adaptation/pathfinder_adaptation.py
blackjax/adaptation/window_adaptation.py
tests/adaptation/test_adaptation.py
tests/mcmc/test_sampling.py

This PR allows for AdaptationInfo to be filtered during the window_adaptation process.  Always storing all the auxiliary information can lead to substantial excess memory usage. 
In response to: https://github.com/blackjax-devs/blackjax/issues/667
I put some initial changes here but it seems like this change applies to the other adaptation algorithms.  Perhaps it's worth moving return_all_adapt_info and get_filter_adapt_info_fn to adaptation/base.py and enabling filtering for the other adaptation algorithms.  But I thought I'd get some perspectives before going down that path. 
Let me know any thoughts / changes

Enable fitlering of AdaptationInfo

---

blackjax/adaptation/window_adaptation.py

Window adaptation did not previously accept an `integrator` argument, but instead used `velocity_verlet`. This was restrictive, since a user may want to run NUTS or HMC with a different integrator (such as `mclachlan`). They can do so, but then cannot use window adaptation. This PR addresses that shortcoming.

Make Window Adaptation Take Integrator As Argument

---

blackjax/mcmc/mclmc.py

This is a small change which addresses quite a severe bug, namely that kwargs.get was not picking up the intended argument (because it was not passed as a kwarg)

FIX KWARG BUG

---

blackjax/adaptation/mclmc_adaptation.py
blackjax/util.py

Avoiding unnecessary unpacking.

Apply function on pytree directly.

---

blackjax/smc/adaptive_tempered.py
blackjax/smc/base.py
blackjax/smc/tempered.py
tests/smc/test_inner_kernel_tuning.py
tests/smc/test_kernel_compatibility.py
tests/smc/test_smc.py
tests/smc/test_tempered_smc.py

Allows for `mcmc_parameters` to be passed to the mcmc kernel as shared parameters prior to applying vmap.  Thus shared parameters will not need to be duplicated for each individual particle.
This change filters `mcmc_parameters` by the length of the first dimension.  Any parameters with length 1 are considered shared (note this is also acceptable in the case of just a single particle) and the rest are unshared.  Shared parameters are then closed over before applying vmap so they don't need duplication.  The behavior remains the same for shared parameters that are duplicated as they are just treated as unshared as before.  This seems like the most reasonable way to handle shared parameters but let me know.
Related to https://github.com/blackjax-devs/blackjax/issues/690
cc @ciguaran
Some …

Enable shared mcmc parameters with tempered smc

---

blackjax/mcmc/termination.py

Removes explicit looping for calculating the uturn checks to perform and replaces it with bitwise calculations.
I don't see much performance difference with a cpu backend but it gives ~30% boost with gpu on some models I'm working with.  This clearly will depend on the model and # of steps though.  For `jnp.bitwise_count((~n & (n + 1)) - 1)`   `(~n & (n + 1))` isolates the bit that changes from 0 to 1 when adding 1 - this is the first zero before the last sequence of ones.  `- 1` clears the above bit and sets all the original last non-zero bits

Convert explicit looping to bit twiddling for iterative_uturn calculations

---

docs/index.md

The jitted step remained unused, leading to the example running with an uncompiled nuts.step. 
Changing this reduces the execution time by a factor of 30 on my system and showcases blackjax' speed.

Fixing typo in example on index page - leading to 30x faster runtime.

---

blackjax/adaptation/window_adaptation.py
blackjax/progress_bar.py
blackjax/util.py

Enables proper progress bar behavior of `progress_bar_scan` under pmap.  However the progress bars are not tied to physical devices since `io_callback` won't expose the device id.  The bars behave as if they are physically tied but are always sorted by most to least complete (they're actually randomly shuffled but one bar will always be first and another last).
I haven't visually tested this under a multi-gpu setup as I don't have an identical pair of gpus - just using `JAX_PLATFORMS='cpu'`
https://github.com/blackjax-devs/blackjax/pull/655 - Related: changes progress bar to tqdm and requires the user to label devices - a different approach

Enable progress bar under pmap

---

blackjax/adaptation/window_adaptation.py
blackjax/progress_bar.py
blackjax/util.py

Cleans up progress bar handling as discussed in https://github.com/blackjax-devs/blackjax/pull/712 - hides the details of running with/without a progress bar.  It turns out the api change in https://github.com/blackjax-devs/blackjax/pull/712 will sometimes break pymc's blackjax based sampling due to the additional carry required and direct use of progress_bar_scan.  This allows for a simpler fix in those scenarios.
@zaxtax This seemed like the most reasonable way to wrap - is it similar to what you were thinking?

wrapper for progress _bar_scan

---

blackjax/mcmc/barker.py
blackjax/mcmc/metrics.py
tests/mcmc/test_barker.py
tests/mcmc/test_metrics.py
tests/mcmc/test_sampling.py

This PR attempts to add a preconditioning matrix to the barker proposal implementation, as in appendix G of https://arxiv.org/abs/1908.11812
- Relevant discussion #723 
- Relevant issue #725 
- I changed the `_compute_acceptance_probability` to be flat given how it was necessary to matrix-multiply with the pre-conditioning matrix. Is that OK? 
- Do I need to update the PDF?  (not used anywhere in the codebase)
- It's not very clear in the Barker paper but the step_size (sigma) is a 'global scale' and the inverse mass matrix is separate.  See implementation from authors here (in R) - https://github.com/gzanella/barker/blob/master/functions.R
Consider opening a **Draft PR** if your work is still in progress but you …

Add pre-conditioning matrix to Barker proposal

---

blackjax/adaptation/mclmc_adaptation.py
blackjax/diagnostics.py

PR for https://github.com/blackjax-devs/blackjax/issues/777
Fix MCLMC number of integration steps for tuning, and allow initial guess for parameters.
I just don't know @reubenharry if you prefer `make_L_step_size_adaptation` to also return the number of steps as in `adjusted_mclmc_make_L_step_size_adaptation`, or to compute it outside the function. I opted for latter as the least modifying update.

MCLMC adaptation total num steps and initial guess

---

blackjax/smc/inner_kernel_tuning.py
blackjax/smc/pretuning.py
blackjax/smc/tuning/from_particles.py
tests/smc/test_inner_kernel_tuning.py

- Right now we have two mechanisms for parameter update within SMC: tuning and pretuning. This PR adds the possibility of using both at the same time. 
- Renames and modifies mass_matrix_from_particles, since we actually care about the inverse one.
- Extracts default measure factory to add for some user friendly error messages

SMC: Joint tuning and pretuning
