blackjax-devs/blackjax

- blackjax/hmc.py
As per title.
Tagging @rlouf.
Based on Twitter conversation: https://twitter.com/ericmjl/status/1350053510876962819
> add disambiguation of what "potential energy function" is

- README.md
Going to self merge this one as I doubt anyone will dislike it and it itll set the coverage status for master so diffs become useful in PRs.
In the event someone really dislikes this let me know so I can apologize profusely and then revert
> Add Code Coverage badge

- notebooks/Introduction.ipynb
Adding a very basic introduction notebook. Going to add some more explanatory text and figures to make this easier to read in the coming days.
Feel free to make any suggestions to spice this up some or any other ideas you'd like to see.
> Add introduction notebook

- blackjax/inference/metrics.py
- tests/test_metrics.py
Getting some mypy failures that I think are unrelated to the code change but can investigate later
> Refactored gaussian_euclidean and added some tests

- blackjax/adaptation/mass_matrix.py
- blackjax/adaptation/step_size.py
- blackjax/inference/base.py
- blackjax/inference/metrics.py
- blackjax/inference/proposal.py
- blackjax/inference/trajectory.py
- blackjax/nuts.py
- blackjax/stan_warmup.py
- tests/test_sampling.py
- tests/test_trajectory.py
See #46 for a description of the issue.
> Fix HMC failure on simple targets

- blackjax/inference/trajectory.py
https://github.com/blackjax-devs/blackjax/issues/53
> fixes issue #53

- blackjax/hmc.py
- blackjax/inference/integrators.py
- blackjax/nuts.py
- tests/test_integrators.py
> Add higher-order integrators

- blackjax/inference/integrators.py
> remove @jax.jit in yoshida and mclachlan integrators (#60)

- notebooks/use_with_pymc3.ipynb
This PR simply adds the notebook from #27.
> Added example of how to run on PyMC3 models

- examples/use_with_pymc3.ipynb
> Make the PyMC example run on version 4

- examples/use_with_pymc.ipynb
Updates this notebook to use pymc4 correctly. Also removes the negation in the density function as blackjax does not expect a potential function but the actual density function.
> Fix example notebook to use pymc 4

- blackjax/__init__.py
- blackjax/kernels.py
- blackjax/mcmc/__init__.py
- blackjax/mcmc/diffusion.py
- blackjax/mcmc/mala.py
- docs/sampling.rst
- tests/test_sampling.py
Same as #152, with one commit.
> Add the MALA sampling algorithm

- .github/workflows/test.yml
- blackjax/kernels.py
- blackjax/mcmc/hmc.py
- blackjax/mcmc/integrators.py
- blackjax/mcmc/nuts.py
- tests/test_integrators.py
- tests/test_sampling.py
As discussed here: https://github.com/blackjax-devs/blackjax/issues/201
I went ahead and tried adding the option to pass custom gradients, and added some basic tests that verify that things still work with custom gradients (in this case, I just used forward mode gradients).
Feedback on API very welcome - this was the simplest design I could think of.  I haven't finished changing the code everywhere, but wanted to hear comments on API before going further.
> API for specifying custom gradients.

- blackjax/__init__.py
- blackjax/kernels.py
- blackjax/mcmc/gradient_estimators.py
- blackjax/sgmcmc/__init__.py
- blackjax/sgmcmc/diffusion.py
- blackjax/sgmcmc/gradients.py
- blackjax/sgmcmc/sgld.py
- docs/sampling.rst
- examples/SGLD.ipynb
- tests/test_sampling.py
With the gradient estimator in Robbins & Monro (1951). Closes #131.
> Implement stochastic gradient langevin dynamics

- blackjax/adaptation/window_adaptation.py
- blackjax/kernels.py
- tests/test_sampling.py
Following what is done in Stan: https://mc-stan.org/docs/2_23/reference-manual/hmc-algorithm-parameters.html
Closes #218
> Set target_acceptance_rate=0.8 in window adaptation

- .github/PULL_REQUEST_TEMPLATE.md
Issue: [Add PR templates](https://github.com/blackjax-devs/blackjax/issues/199)
PR: [PR#230](https://github.com/blackjax-devs/blackjax/pull/230)
> Add PR template (issue#199)

- blackjax/adaptation/window_adaptation.py
- tests/test_adaptation.py
Closes #267. I also added a small test to ensure the schedule is the correct length.
> Fixed length of adaptation window when there are < 20 steps

- docs/conf.py
- docs/howtos.rst
- docs/index.rst
- examples/PeriodicOrbitalMCMC.md
- examples/README.md
- examples/RegimeSwitchingModel.md
- examples/SparseLogisticRegression.md
- examples/aesara.md
- examples/change_of_variable_hmc.md
- examples/numpyro.md
- examples/pymc.md
- examples/tfp.md
- requirements-doc.txt
- Fix import error in PeriodicOrbitalMCMC.md
- Clean up and improve change_of_variable_hmc.md
> Example clean up

- .github/workflows/build_documentation.yml
- .github/workflows/publish_documentation.yml
- docs/_static/custom.css
I copy/pasted the examples in the [Gitub documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run). I also removed that ugly grey color of the navigation bar. We shoud also change the font soon.
> Fix the documentation workflow

- .github/workflows/build_documentation.yml
- .github/workflows/publish_documentation.yml
That's not ideal, but it's better than not understanding what I am doing.
> Duplicate the job that builds the docs across workflows

- docs/conf.py
> Turn notebook execution back on

- examples/HierarchicalBNN.md
- examples/Introduction.md
- examples/LogisticRegression.md
- examples/SGMCMC.md
- examples/SparseLogisticRegression.md
There were a few imperfections on the formatting left.
> Tweak the display of notebook examples

- README.md
Reverts blackjax-devs/blackjax#338
> Revert "s/BlackJAX/Blackjax in README"

- blackjax/__init__.py
- setup.py
> Add LICENCE to distributed source

- docs/sampling.rst
> Fix "Langeving" typo in sampling.rst

- examples/SGMCMC.md
This updates the MNIST example to use Flax. Provides modest speed-ups.
Fixes #326
> Refactor MNIST example to use Flax

- blackjax/mcmc/marginal_latent_gaussian.py
- setup.cfg
- tests/test_resampling.py
> Make tests fail on uncaught warnings

- .github/workflows/publish_documentation.yml
- README.md
- blackjax/sgmcmc/diffusions.py
- blackjax/sgmcmc/sghmc.py
- blackjax/sgmcmc/sgld.py
- docs/adaptation.rst
- docs/howto_use_ppl.rst
- docs/index.rst
- docs/mcmc.rst
- docs/sgmcmc.rst
- docs/smc.rst
- docs/vi.rst
- examples/GP_EllipticalSliceSampler.md
- examples/LogisticRegression.md
- examples/LogisticRegressionWithLatentGaussianSampler.md
- examples/Pathfinder.md
- examples/RegimeSwitchingModel.md
- examples/SGMCMC.md
- examples/SparseLogisticRegression.md
- examples/change_of_variable_hmc.md
- examples/howto_other_frameworks.md
- examples/howto_sample_multiple_chains.md
- examples/howto_use_aesara.md
- examples/howto_use_numpyro.md
- examples/howto_use_tfp.md
- requirements-doc.txt
This PR cleans and reorganizes the examples. It also fixes an issue with SgHMC encoutered while running the notebooks. It is **bad** that this failed silently and we should seriously consider #412
> Clean examples

- .github/workflows/nightly.yml
- README.md
- docs/conf.py
- mypy.ini
- setup.cfg
- setup.py
> Add support for nightly releases

- blackjax/adaptation/mass_matrix.py
- blackjax/adaptation/meads.py
- blackjax/adaptation/step_size.py
- blackjax/mcmc/elliptical_slice.py
- blackjax/mcmc/ghmc.py
- blackjax/mcmc/hmc.py
- blackjax/mcmc/integrators.py
- blackjax/mcmc/mala.py
- blackjax/mcmc/marginal_latent_gaussian.py
- blackjax/mcmc/metrics.py
- blackjax/mcmc/nuts.py
- blackjax/mcmc/proposal.py
- blackjax/mcmc/rmh.py
- blackjax/mcmc/termination.py
- blackjax/mcmc/trajectory.py
- blackjax/optimizers/dual_averaging.py
- blackjax/optimizers/lbfgs.py
- blackjax/sgmcmc/diffusions.py
- blackjax/sgmcmc/gradients.py
- blackjax/sgmcmc/sghmc.py
- blackjax/sgmcmc/sgld.py
- blackjax/smc/adaptive_tempered.py
- blackjax/smc/base.py
- blackjax/smc/ess.py
- blackjax/smc/tempered.py
- blackjax/vi/pathfinder.py
Time to clean those docstrings!
> Use NumPy style for linebreak at end of docstring

- blackjax/adaptation/step_size.py
- blackjax/optimizers/dual_averaging.py
- requirements.txt
- setup.py
- tests/test_optimizers.py
> Fix import for `blackjax.optimizers.dual_averaging`

- docs/examples/TemperedSMC.md
Tempered SMC notebook got broken after a recent PR that change the interface, fixing it.
> Fixing TemperedSMC example

- docs/examples/Introduction.md
Fixed small typo in [Introduction Example](https://blackjax-devs.github.io/blackjax/examples/Introduction.html#) raising error.
> Fix the Introduction Example

- blackjax/optimizers/lbfgs.py
- blackjax/util.py
> Replace uses of internal JAX NumPy utils with public API functions.

- .pre-commit-config.yaml
- blackjax/kernels.py
- blackjax/mcmc/ghmc.py
- blackjax/mcmc/rmh.py
- blackjax/sgmcmc/diffusions.py
- blackjax/sgmcmc/sgld.py
- blackjax/smc/resampling.py
- blackjax/vi/meanfield_vi.py
- setup.cfg
- tests/mcmc/test_sampling.py
- tests/smc/test_smc.py
- tests/smc/test_smc_ess.py
- tests/smc/test_tempered_smc.py
The `isort` dependency currently fails to install. This PR bumps the version numbers of every dependency.
> Update pre-commit dependencies

- blackjax/adaptation/mass_matrix.py
- blackjax/adaptation/meads_adaptation.py
- blackjax/adaptation/step_size.py
- blackjax/adaptation/window_adaptation.py
- blackjax/diagnostics.py
- blackjax/kernels.py
- blackjax/mcmc/elliptical_slice.py
- blackjax/mcmc/integrators.py
- blackjax/mcmc/irmh.py
- blackjax/mcmc/metrics.py
- blackjax/mcmc/nuts.py
- blackjax/mcmc/periodic_orbital.py
- blackjax/mcmc/proposal.py
- blackjax/mcmc/trajectory.py
- blackjax/optimizers/dual_averaging.py
- blackjax/optimizers/lbfgs.py
- blackjax/progress_bar.py
- blackjax/sgmcmc/csgld.py
- blackjax/sgmcmc/diffusions.py
- blackjax/sgmcmc/gradients.py
- blackjax/smc/base.py
- blackjax/vi/meanfield_vi.py
- blackjax/vi/pathfinder.py
- docs/bib.rst
- docs/conf.py
- docs/index.md
- docs/refs.bib
- requirements-doc.txt
> Handle references using sphinxcontrib-bibtex with the BibTeX alpha style

- blackjax/kernels.py
> Fix SGLD and SGHMC docstrings

- pyproject.toml
- requirements-doc.txt
> Use latest release of optax

- blackjax/util.py
> Add utility function to demonstrate unflattening of arrays

- README.md
- docs/examples/howto_custom_gradients.md
- docs/examples/howto_metropolis_within_gibbs.md
- docs/examples/howto_other_frameworks.md
- docs/examples/howto_sample_multiple_chains.md
- docs/examples/howto_use_aesara.md
- docs/examples/howto_use_numpyro.md
- docs/examples/howto_use_oryx.md
- docs/examples/howto_use_pymc.md
- docs/examples/howto_use_tfp.md
- docs/examples/quickstart.md
- docs/index.md
- requirements-doc.txt
- Consistent PRNGKey initialization using current date
- Avoid PRNGKey reuse
- Minor styling improvement
> Documentation clean up

- blackjax/__init__.py
- blackjax/vi/__init__.py
- blackjax/vi/schrodinger_follmer.py
- docs/refs.bib
- tests/vi/test_schrodinger_follmer.py
See this:
https://github.com/blackjax-devs/blackjax/issues/601
> Implements the Schrödinger-Föllmer algorithm.

- blackjax/__init__.py
- blackjax/adaptation/chees_adaptation.py
- blackjax/mcmc/dynamic_hmc.py
- blackjax/mcmc/hmc.py
- tests/mcmc/test_trajectory.py
Close #620, #618
cc @reubenharry
> Refactor dynamic_hmc out of hmc.py

- blackjax/mcmc/integrators.py
- blackjax/mcmc/mclmc.py
- tests/mcmc/test_integrators.py
to match default implmentation in https://github.com/JakobRobnik/MicroCanonicalHMC/blob/master/mclmc/dynamics.py
Close: #625. cc @reubenharry
> Update noneuclidean integrator

- docs/index.md
> Indexing the notebook showing how to reproduce the GIF.

- requirements-doc.txt
Fix https://github.com/blackjax-devs/blackjax/issues/665
> Update jax version requirements

- blackjax/mcmc/integrators.py
> Change isokinetic_integrator generation API

- docs/examples/howto_sample_multiple_chains.md
- docs/examples/quickstart.md
- tests/smc/__init__.py
- tests/smc/test_inner_kernel_tuning.py
> Add logjac to logdensity_fn
